### ISSUE TITLE
smallest executable size

### ISSUE THREAD

**Issue by akkuman** [byt3bl33d3r/OffensiveNim#2] opened 2020-11-23 16:37 UTC
example:

https://github.com/elddy/NimScan

`nim c -d:danger -d:strip --opt:size --passc=-flto --passl:-flto NimScan.nim`

665.54 KB

`nim c -d:danger --opt:size --passc=-flto --passl:-s NimScan.nim`

285.00 KB

**Comment by byt3bl33d3r** [comment] 2020-11-23 17:27
I'm confused, whats the issue exactly? Those flags are outlined in the readme and the makefile

**Comment by byt3bl33d3r** [comment] 2020-11-24 16:48
Closing since i don't know what the issue is exactly. Feel free to clarify.

**Closed by byt3bl33d3r** 2020-11-24 16:48 UTC
